package com.example.nickelfoxassignment

object Constants {
    const val ONE = "1"
    const val TWO = "2"
    const val THREE = "3"
    const val FOUR = "4"
    const val FIVE = "5"
    const val SIX = "6"
    const val SEVEN = "7"
    const val EIGHT = "8"
    const val NINE = "9"
    const val ZERO = "0"
    const val DOUBLE_ZERO = "00"
    const val SIN = "sin "
    const val COS = "cos "
    const val TAN = "tan "
    const val ADD = "+"
    const val SUBTRACT = "-"
    const val MULTIPLY = "*"
    const val DIVIDE = "/"
    const val MOD = "%"
    const val DOT = "."
    const val DECIMAL_FORMAT = "0.######"
    const val DIVIDE_ = "÷"
    const val MULTIPLY_ = "×"
}